from setuptools import setup, find_packages

setup(
    name="crypto_arbitrage",
    version="0.1.0",
    description="加密货币套利交易系统",
    author="maodou",
    author_email="maodou@example.com",
    packages=find_packages(),
    install_requires=[
        "python-dotenv>=0.19.0",
        "ccxt>=4.0.0",
        "numpy>=1.21.0",
        "pandas>=1.3.0",
        "tensorflow>=2.10.0",
        "scikit-learn>=1.0.0",
        "fastapi>=0.68.0",
        "uvicorn>=0.15.0",
        "psycopg2-binary>=2.9.1",
        "influxdb-client>=1.24.0",
        "redis>=4.0.0",
        "aiohttp>=3.8.0",
        "python-telegram-bot>=13.7",
        "requests>=2.26.0",
        "pydantic>=1.8.2",
        "loguru>=0.5.3",
        "PyYAML>=5.4.1",
        "prometheus-client>=0.11.0",
        "psutil>=5.8.0"
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Financial and Insurance Industry",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Office/Business :: Financial :: Investment",
    ],
) 